# Generated by Django 5.2.5 on 2026-10-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_user_fullname_user_company_organizationunit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='role',
            name='company',
        ),
        migrations.RemoveField(
            model_name='organizationunit',
            name='company',
        ),
        migrations.RemoveField(
            model_name='organizationunit',
            name='level',
        ),
        migrations.RemoveField(
            model_name='organizationunit',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='organization_unit',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='role',
        ),
        migrations.DeleteModel(
            name='OrganizationUnit',
        ),
    ]
